name: Project2 Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to AWS
        env:
          AWS_KEY: ${{ secrets.AWS_KEY }}
          AWS_HOST: ${{ secrets.AWS_HOST }}
          AWS_USER: ${{ secrets.AWS_USER }}
        run: |
          echo "$AWS_KEY" > key.pem
          chmod 400 key.pem
          ssh -o StrictHostKeyChecking=no -i key.pem $AWS_USER@$AWS_HOST "cd project2 && git pull && docker-compose down && docker-compose up -d --build"
          rm key.pem
